'use strict';

const BATCH_STATUS = Object.freeze({
  UPLOADED: 'UPLOADED',
  VALIDATING: 'VALIDATING',
  VALIDATED: 'VALIDATED', // validation done, waiting for "Import Valid Records"
  READY: 'READY',
  PROCESSING: 'PROCESSING',
  PAUSED: 'PAUSED',
  COMPLETED: 'COMPLETED',
  COMPLETED_WITH_FAILURES: 'COMPLETED_WITH_FAILURES',
  CANCELLED: 'CANCELLED',
});

const RECORD_STATUS = Object.freeze({
  PENDING: 'PENDING',
  QUEUED: 'QUEUED',
  PROCESSING: 'PROCESSING',
  SENT: 'SENT',
  DELIVERED: 'DELIVERED',
  READ: 'READ',
  FAILED: 'FAILED',
  INVALID_NUMBER: 'INVALID_NUMBER',
  NOT_ON_WHATSAPP: 'NOT_ON_WHATSAPP',
  RATE_LIMITED: 'RATE_LIMITED',
  PROVIDER_ERROR: 'PROVIDER_ERROR',
  RETRY_SCHEDULED: 'RETRY_SCHEDULED',
  CANCELLED: 'CANCELLED',
});

const S = RECORD_STATUS;

const SUCCESS_STATUSES = [S.SENT, S.DELIVERED, S.READ];
const FAILURE_STATUSES = [S.FAILED, S.INVALID_NUMBER, S.NOT_ON_WHATSAPP, S.RATE_LIMITED, S.PROVIDER_ERROR];
const IN_PROGRESS_STATUSES = [S.PENDING, S.QUEUED, S.PROCESSING, S.RETRY_SCHEDULED];
const TERMINAL_STATUSES = [...SUCCESS_STATUSES, ...FAILURE_STATUSES, S.CANCELLED];
const CLAIMABLE_STATUSES = [S.QUEUED, S.RETRY_SCHEDULED];
// Failures a human may re-queue with "Retry Failed" (still subject to retry_eligible).
const MANUAL_RETRY_STATUSES = [S.FAILED, S.RATE_LIMITED, S.PROVIDER_ERROR];

// Delivery progress only moves forward: a late "delivered" never overwrites "read".
const SUCCESS_RANK = { [S.SENT]: 1, [S.DELIVERED]: 2, [S.READ]: 3 };

const FILTERS = Object.freeze({
  all: null,
  pending: [S.PENDING, S.QUEUED, S.RETRY_SCHEDULED],
  processing: [S.PROCESSING],
  sent: [S.SENT],
  delivered: [S.DELIVERED],
  read: [S.READ],
  failed: [S.FAILED, S.RATE_LIMITED, S.PROVIDER_ERROR],
  invalid_number: [S.INVALID_NUMBER],
  not_on_whatsapp: [S.NOT_ON_WHATSAPP],
  cancelled: [S.CANCELLED],
  retry_scheduled: [S.RETRY_SCHEDULED],
  all_failures: FAILURE_STATUSES,
});

module.exports = {
  BATCH_STATUS,
  RECORD_STATUS,
  SUCCESS_STATUSES,
  FAILURE_STATUSES,
  IN_PROGRESS_STATUSES,
  TERMINAL_STATUSES,
  CLAIMABLE_STATUSES,
  MANUAL_RETRY_STATUSES,
  SUCCESS_RANK,
  FILTERS,
};
